{% set name = "arize-phoenix" %}
{% set version = "5.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/arize_phoenix-{{ version }}.tar.gz
  sha256: 1f18c551572ef03570cf52ee80d5a1ead4f99e072e59b53206a7bb8719b6b14e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<3.13
    - hatchling
    - hatch-jupyter-builder
    - pip
  run:
    - python >=3.8,<3.13
    - scikit-learn
    - numpy
    - pandas >=1.0
    - umap-learn
    - hdbscan >=0.8.33
    - starlette
    - uvicorn
    - psutil
    - strawberry-graphql ==0.236.0
    - pyarrow
    - typing-extensions >=4.5
    - scipy
    - wrapt
    - sortedcontainers
    - protobuf >=3.20, <5.0
    - jinja2
    - ddsketch
    - tqdm
    - requests
    - opentelemetry-sdk
    - opentelemetry-proto >=1.12.0
    - opentelemetry-exporter-otlp
    - openinference-semantic-conventions >=0.1.9
    - openinference-instrumentation >=0.1.12
    - openinference-instrumentation-langchain >=0.1.26
    - openinference-instrumentation-llama-index >=2.2.1
    - openinference-instrumentation-openai >=0.1.11
    - sqlalchemy >=2.0.4, <3
    - greenlet !=0.4.17
    - alembic >=1.3.0, <2
    - aiosqlite
    - aioitertools
    - sqlean.py >=3.45.1
    - cachetools
    - httpx
    - python-multipart
    - arize-phoenix-evals >=0.13.1
    - fastapi
    - pydantic >=1.0,!=2.0.*,<3
    - pyjwt


test:
  imports:
    - phoenix

about:
  summary: ML Observability in your notebook
  home: https://github.com/Arize-ai/phoenix
  doc_url: https://docs.arize.com/phoenix
  license: Elastic-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - anticorrelator
    - mikeldking
    - rogerhyang
    - michaelschiff
    - fjcasti1
    - axiomofjoy
