{% set name = "arize-phoenix" %}
{% set version = "0.0.27" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/arize_phoenix-{{ version }}.tar.gz
  sha256: d8bda0e4192e292d5e0fb5878d36150feccb69280048cf5e0e1270d084a11a7e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<3.12
    - hatchling
    - hatch-jupyter-builder
    - pip
  run:
    - python >=3.8,<3.12
    - numpy
    - pandas
    - umap-learn
    - hdbscan
    - starlette
    - uvicorn
    - psutil
    - strawberry-graphql ==0.178.0
    - pyarrow
    - typing-extensions
    - scipy
    - portpicker
    - wrapt

test:
  imports:
    - phoenix
  commands:
    - pip check
  requires:
    - pip

about:
  summary: ML Observability in your notebook
  home: https://github.com/Arize-ai/phoenix
  doc_url: https://docs.arize.com/phoenix
  license: Elastic-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mikeldking
    - rogerhyang
    - michaelschiff
    - fjcasti1
    - axiomofjoy
