{% set name = "arize-phoenix" %}
{% set version = "3.18.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/arize_phoenix-{{ version }}.tar.gz
  sha256: f2f7958f0ae2b477ba6fe10d0b4998e627073b64cabacda881c01a37455e29fe

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<3.13
    - hatchling
    - hatch-jupyter-builder
    - pip
  run:
    - python >=3.8,<3.13
    - scikit-learn
    - numpy
    - pandas
    - umap-learn
    - hdbscan >=0.8.33
    - starlette
    - uvicorn
    - psutil
    - strawberry-graphql ==0.208.2
    - pyarrow
    - typing-extensions >=4.5
    - scipy
    - wrapt
    - sortedcontainers
    - protobuf >=3.20, <5.0
    - jinja2
    - ddsketch
    - tqdm
    - requests
    - opentelemetry-sdk
    - opentelemetry-proto
    - opentelemetry-exporter-otlp
    - openinference-semantic-conventions >=0.1.5
    - openinference-instrumentation
    - openinference-instrumentation-openai >=0.1.3
    - openinference-instrumentation-langchain >=0.1.11
    - openinference-instrumentation-llama-index >=1.1.1


test:
  imports:
    - phoenix

about:
  summary: ML Observability in your notebook
  home: https://github.com/Arize-ai/phoenix
  doc_url: https://docs.arize.com/phoenix
  license: Elastic-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - anticorrelator
    - mikeldking
    - rogerhyang
    - michaelschiff
    - fjcasti1
    - axiomofjoy
