{% set name = "arize-phoenix" %}
{% set version = "5.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/arize_phoenix-{{ version }}.tar.gz
  sha256: 7b37270ce2d91cc4125685f229a304f5167f6978a0256f34796b320154dba898

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<3.13
    - hatchling
    - hatch-jupyter-builder
    - pip
  run:
    - python >=3.9,<3.13
    - aioitertools
    - aiosqlite
    - alembic >=1.3.0, <2
    - arize-phoenix-evals >=0.13.1
    - arize-phoenix-otel >=0.5.1
    - authlib
    - cachetools
    - hdbscan >=0.8.38
    - ddsketch
    - fastapi
    - greenlet !=0.4.17
    - grpc-interceptor
    - grpcio
    - httpx
    - jinja2
    - numba >=0.60.0
    - numpy
    - openinference-instrumentation >=0.1.12
    - openinference-semantic-conventions >=0.1.9
    - opentelemetry-exporter-otlp
    - opentelemetry-proto >=1.12.0
    - opentelemetry-sdk
    - opentelemetry-semantic-conventions
    - pandas >=1.0
    - protobuf >=3.20, <5.0
    - psutil
    - pyarrow
    - pydantic >=1.0,!=2.0.*,<3
    - python-multipart
    - scikit-learn
    - scipy
    - sqlalchemy >=2.0.4, <3
    - sqlean.py >=3.45.1
    - starlette
    - strawberry-graphql ==0.236.0
    - tqdm
    - typing-extensions >=4.6
    - umap-learn
    - uvicorn
    - wrapt


test:
  imports:
    - phoenix

about:
  summary: ML Observability in your notebook
  home: https://github.com/Arize-ai/phoenix
  doc_url: https://docs.arize.com/phoenix
  license: Elastic-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - anticorrelator
    - mikeldking
    - rogerhyang
    - michaelschiff
    - fjcasti1
    - axiomofjoy
