{% set name = "arize-phoenix" %}
{% set version = "3.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/arize_phoenix-{{ version }}.tar.gz
  sha256: dbbc0018df3b8c40d111ed7f903d8510508db96c51378859c79a839c515d915f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<3.12
    - hatchling
    - hatch-jupyter-builder
    - pip
  run:
    - python >=3.8,<3.12
    - cython <3
    - scikit-learn <1.3.0
    - numpy
    - pandas
    - umap-learn
    - hdbscan >=0.8.33, <1.0.0
    - starlette
    - uvicorn
    - psutil
    - strawberry-graphql ==0.208.2
    - pyarrow
    - typing-extensions >=4.5, <5
    - scipy
    - wrapt
    - sortedcontainers
    - protobuf >=3.20, <5.0
    - jinja2
    - ddsketch
    - tqdm
    - requests
    - opentelemetry-sdk
    - opentelemetry-proto
    - opentelemetry-exporter-otlp
    - openinference-semantic-conventions
    - openinference-instrumentation-openai
    - openinference-instrumentation-langchain
    - openinference-instrumentation-llama-index

test:
  imports:
    - phoenix

about:
  summary: ML Observability in your notebook
  home: https://github.com/Arize-ai/phoenix
  doc_url: https://docs.arize.com/phoenix
  license: Elastic-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - anticorrelator
    - mikeldking
    - rogerhyang
    - michaelschiff
    - fjcasti1
    - axiomofjoy
