{% set name = "arize-phoenix" %}
{% set version = "8.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/arize_phoenix-{{ version }}.tar.gz
  sha256: ad0b292381c4fd7dfb79f83fa3278f42bc54fdbb4f7325b1635de0d873e78bf4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-jupyter-builder
    - pip
  run:
    - python >={{ python_min }},<3.13
    - aioitertools
    - aiosqlite
    - alembic >=1.3.0, <2
    - arize-phoenix-client
    - arize-phoenix-evals >=0.13.1
    - arize-phoenix-otel >=0.5.1
    - authlib
    - cachetools
    - ddsketch
    - fastapi
    - fast_hdbscan >=0.2.0
    - greenlet !=0.4.17
    - grpc-interceptor
    - grpcio
    - httpx
    - jinja2
    - numba >=0.60.0
    - numpy
    - openinference-instrumentation >=0.1.12
    - openinference-semantic-conventions >=0.1.9
    - opentelemetry-exporter-otlp
    - opentelemetry-proto >=1.12.0
    - opentelemetry-sdk
    - opentelemetry-semantic-conventions
    - pandas >=1.0
    - protobuf >=3.20, <5.0
    - psutil
    - pyarrow
    - pydantic >=2.1.0,<3
    - python-multipart
    - scikit-learn
    - scipy
    - sqlalchemy >=2.0.4, <3
    - sqlean.py >=3.45.1
    - starlette
    - strawberry-graphql ==0.253.1
    - tqdm
    - typing-extensions >=4.6
    - umap-learn
    - uvicorn
    - websockets
    - wrapt


test:
  requires:
    - python {{ python_min }}
  imports:
    - phoenix

about:
  summary: ML Observability in your notebook
  home: https://github.com/Arize-ai/phoenix
  doc_url: https://docs.arize.com/phoenix
  license: Elastic-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - anticorrelator
    - mikeldking
    - rogerhyang
    - michaelschiff
    - fjcasti1
    - axiomofjoy
